### ISSUE TITLE
Does exist any video?

### ISSUE THREAD

**Issue by jabrena** [antbern/gridmap-slam-robot#1]
HI @antbern.

does exist any video running the system?

Juan Antonio

**Comment by antbern** [comment]
Hello @jabrena!

Here is a link to a video i took of the system in action:
[https://photos.app.goo.gl/9LCzzc31TMR4rb7r5](https://photos.app.goo.gl/9LCzzc31TMR4rb7r5)

I also intend to document both the software and hardware in the future - it's on my TODO list!

Anton Berneving

**Comment by jabrena** [comment]
The video is cool.

Can you consider to add support for EV3?

**Comment by jabrena** [comment]
I suppose that you are using a wired serial connection with Arduino with an USB cable, is it right?

I could create a client from Robot side to offer an interface for the robot data that your app require.

What is the data that it is necessary to expose?

**Comment by antbern** [comment]
I have not done any work with the EV3 before, although I own one of the earlier Mindstorms NXT 2.0 kits.

The robot consistst of an Arduino that controls both dc motors and their encoders as well as the stepper motor and the two VL53l0X ranging modules. It sends ranging data (angle and distance) together with 
relative encoder counts over a wired (USB) serial connection to my computer running the software.

The software also sends desired motor velocities back to the Arduino for controling the robot.

The interface would thus need to expose the following:
* Encoder motor counts 
* Angle and distance from ranging sensor
* A way to send desired velocity back to the robot

Please note that the project is by no means complete - there may be quite a few changes made to the software and the protocol in the future!

**Comment by jabrena** [comment]
Hi @antbern,

I continue interested in the integration. 
Any new advanced in the visualization. I watched the last video and it was very promising.

Juan Antonio
